server:
  port: 8888

spring:
  application:
    name: mall-front
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  database: mall
  expire:
    common: 86400 # 24小时
  key:
    user: 'ums:member'
    prefix:
      orderId: 'portal:orderId:'

jwt:
  secret: tuling-mall-portal  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字


secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /user/**
      - /product/**
      - /home/**
      - /order/alipay/fallback/**
      - /order/wechatPay/fallback/**
      - /static/qrcode/**


